# Generated by Django 4.0 on 2022-01-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='recipent',
        ),
    ]
