# Generated by Django 4.0 on 2022-01-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_rename_recipient_message_recipent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
